spring:
  application:
    name: Config-default
eureka:
  instance:
    prefer-ip-address: true
    appname: USER-SERVICESER
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
